server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: showtimes-service
          uri: lb://showtimes-service
          predicates:
            - Path=/Parcial2/api/v1/showtimes/**
        - id: movies-service
          uri: lb://movies-service
          predicates:
            - Path=/Parcial2/api/v1/movies/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/Parcial2/api/v1/user/**
        - id: bookings-service
          uri: lb://bookings-service
          predicates:
            - Path=/Parcial2/api/v1/bookings/**    
