spring:
  application:
    name: shopping-service
  profiles:
    active: dev
server:
  servlet:
    context-path: /store/api/v1
  port: 9070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
feign:
  circuitbreaker:
    enabled: true
